#!/usr/bin/env python3
"""
Main entry point application of an easy API Restful app for json storage

Authors:
    - Francisco Jesús Díaz Pellejero
    - Miguel de las Heras Fuentes
"""

import os
import json

from secrets import token_urlsafe
from threading import Timer, Lock
from flask import Flask, request
from flask_restful import Resource, Api


# Custom imports
from app_module import exceptions, entry, check



# --------------------------------------------------------GLOBAL VARIABLES--------------------------------------------------------#
ROOT_DIR = "database/"
g_tokens = {}
lock = Lock()


# --------------------------------------------------------API INICIALIZATION--------------------------------------------------------#
app = Flask(__name__)
api = Api(app, errors=exceptions.ERRORS)


app.config['SERVER_NAME'] = 'myserver.local:5000'


# --------------------------------------------------------METHODS--------------------------------------------------------#
def get_req_args(*args):
    """Process json or form data. URL of files parameters not supported"""
    results = [None] * len(args)
    i = 0

    # Get json data
    json_obj = request.get_json(silent=True, force=True)

    if json_obj:
        for arg in args:
            results[i] = json_obj.get(arg)
            i = i + 1
        return tuple(results)

    # Get form data
    for arg in args:
        results[i] = request.form.get(arg)
        if not results[i]:
            break
        i = i + 1

    return tuple(results)


def write_file(file_path, contents):
    with open(file_path, "w") as file:
        json.dump(contents, file)


def revokeToken(token):
    """Delete with Mutex because the dict.pop operation is not thread safe"""
    with lock:
        g_tokens.pop(token)


#--------------------------------------------------------CLASSES--------------------------------------------------------#
@api.resource('/version', methods=["GET"], provide_automatic_options=False)
class Version(Resource):
    def get(self):
        return {'version': '1.0'}


@api.resource("/signup", methods=["POST"], provide_automatic_options=False)
class Signup(Resource):
    def post(self):
        user, passwd = get_req_args("username", "password")

        if None in (user, passwd):
            raise exceptions.BadRequestUserPass

        if entry.retrieve(user):
            raise exceptions.UserAlreadyExists

        os.mkdir(f"{ROOT_DIR}{user}")

        entry.add(user, passwd)
        token = token_urlsafe(40)
        g_tokens[token] = user
        Timer(300.0, revokeToken, [token]).start()
        return {'access_token': token, 'warning': 'all tokens expire after 5 minutes'}


@api.resource("/login", methods=["POST"], provide_automatic_options=False)
class Login(Resource):
    def post(self):
        user, passwd = get_req_args("username", "password")

        if None in (user, passwd):
            raise exceptions.BadRequestUserPass

        user_entry = entry.retrieve(user)
        if not user_entry:
            raise exceptions.UserDoesNotExist
  
        if not check.password(user_entry, passwd):
            raise exceptions.WrongPass

        token = token_urlsafe(40)
        g_tokens[token] = user
        Timer(300.0, revokeToken, [token]).start()
        return {'access_token': token, 'warning': 'all tokens expire after 5 minutes'}
    


@api.resource("/<string:username>/<string:doc_id>", methods=["GET", "POST", "PUT", "DELETE"], provide_automatic_options=False)
class UserDocuments(Resource):
    
    def __init__(self):
        super().__init__()
        self.auth_header, self.token = check.auth_header()
        
    
    def check_user(self, username):
        if g_tokens.get(self.token) != username:
            raise exceptions.UnauthorizedToken()


    def get(self, username, doc_id):
        self.check_user(username)
        file_path = f"{ROOT_DIR}{username}/{doc_id}"
        
        check.file_exists(file_path)

        with open(file_path) as file:
            data = json.load(file)
        return data


    def post(self, username, doc_id):
        self.check_user(username)
        content = check.json_content(get_req_args("doc_content")[0]) # Tuples with one element return (val, ) so indexing is neccessary here

        file_path = f"{ROOT_DIR}{username}/{doc_id}"

        if os.path.isfile(file_path):
            raise exceptions.FileAlreadyExists


        write_file(file_path, content)

        return {"size": os.path.getsize(file_path)}


    def put(self, username, doc_id):
        self.check_user(username)
        content = check.json_content(get_req_args("doc_content")[0])
        file_path = f"{ROOT_DIR}{username}/{doc_id}"
        
        check.file_exists(file_path)
        write_file(file_path, content)

        return {"size": os.path.getsize(file_path)}
        
    
    def delete(self, username, doc_id):
        self.check_user(username)
        file_path = f"{ROOT_DIR}{username}/{doc_id}"
        check.file_exists(file_path)
        os.remove(file_path)
        return {}



@api.resource("/<string:username>/_all_docs", methods=["GET"], provide_automatic_options=False)
class AllDocuments(Resource):
    
    def __init__(self):
        super().__init__()
        self.auth_header, self.token = check.auth_header()

    def check_user(self, username):
        if g_tokens.get(self.token) != username:
            raise exceptions.UnauthorizedToken()
    
    
    def get(self, username):
        self.check_user(username)
        all_content = {}
        dir_path = f"{ROOT_DIR}{username}"
        files = [f for f in os.listdir(dir_path) if os.path.isfile(os.path.join(dir_path, f))]

        for file in files:
            with open(f"{dir_path}/{file}", "r") as fp:
                all_content.update({file:json.load(fp)})

        return all_content


if __name__ == '__main__':
    app.run(debug=True, ssl_context=("domain.crt", "domain.key"))